
GAME_WIDTH = 1280
GAME_HEIGHT = 720

WINDOW_WIDTH = 384
WINDOW_HEIGHT = 216

TILE_SIZE = 16

--entity const

PLAYER_SPEED = 50

--map const

MAP_W = WINDOW_WIDTH / TILE_SIZE - 2
MAP_H = math.floor(WINDOW_HEIGHT / TILE_SIZE) - 2

MAP_RENDER_X = (WINDOW_WIDTH - (MAP_W * TILE_SIZE)) / 2
MAP_RENDER_Y = (WINDOW_HEIGHT - (MAP_H * TILE_SIZE)) / 2

--tile

-- TILE_TOP_L_CORNER = 
-- TILE_TOP_R_CORNER = 
-- TILE_BOTOM_L_CORNER = 
-- TILE_BOTOM_R_CORNER = 

--TILE_EMPTY = 

--TILE_FLOORS = {}

--TILE_TWALLS = {}
--TILE_BWALLS = {}
--TILE_RWALLS = {}
--TILE_LWALLS = {}
